version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-container
    ports:
      - "5400:5432"
    volumes:
      - ./db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql
    environment:
      POSTGRES_DB: provaJava
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

volumes:
  postgres_data: